name: diffusion
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # dev environment
  - pytest
  - black
  - flake8
  - python=3.10
  # ML
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - huggingface_hub
  - pip:
      - transformers==4.19.2 
      - diffusers 
      - invisible-watermark