name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # dev environment
  - pytest
  - black
  - flake8
  - python=3.10
  # others
  - tqdm
  # ML
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - huggingface_hub
  - pip
  - pip:
      - transformers
      - diffusers 
      - invisible-watermark